### ISSUE TITLE
Decimal values are mangled when using JSON reader but work when using binary reader

### ISSUE THREAD

**Issue by JonRossEventus** [housepower/spark-clickhouse-connector#241] opened 2023-05-16 19:44 UTC
I have an example project using spark version 3.4 and your latest connector. The issue also exists in 3.3.2 of spark. I'm using java 17 to run this. 

I am providing an example project that reproduces the issue with two tests that should pass, but only the binary one is. 

in a nutshell, the output we're getting from our query is 

```
+--------+-------+-------+
|     day|maxHigh| minLow|
+--------+-------+-------+
|20220701|1.43E-7|1.01E-7|
+--------+-------+-------+
```

but should be 

```
+--------+------------+------------+
|     day|     maxHigh|      minLow|
+--------+------------+------------+
|20220701|14.300000000|10.100000000|
+--------+------------+------------+
```

[failingClickhouseConnectorExample.zip](https://github.com/housepower/spark-clickhouse-connector/files/11491463/failingClickhouseConnectorExample.zip)

**Comment by pan3793** [comment] 2023-05-20 20:13
Thanks for reporting this issue, it's caused by the wrong handle of precision, should be fixed in #242

**Closed** 2023-05-21 15:40 UTC
